/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scanclient;
import scanclient.shared;
import scanclient.barcodeObject;
import scanclient.clock;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import scanclient.PlaySound;
/**
 *
 * @author phillip.oegema
 */
public class CheckoutInterface extends javax.swing.JFrame {

    static shared shared;
    clock clock = new clock();
   
    /**
     * Creates new form CheckoutInterface
     */
    public CheckoutInterface() {
        initComponents();
        shared. setupCheckout();
        jTextAreaTechsOnDuty.setText(shared.getNamesOnDuty());
        jTextAreaKeys.setText(shared.getKeysCheckedOut());
        jTextFieldBarcodeInput.requestFocusInWindow();

    }
    
    public void begin(){
        jTextAreaTechsOnDuty.setText(shared.getNamesOnDuty());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEnter = new javax.swing.JButton();
        jTextFieldBarcodeInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTechsOnDuty = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaKeys = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 975));

        jButtonEnter.setText("Enter");
        jButtonEnter.setFocusCycleRoot(true);
        jButtonEnter.setFocusTraversalPolicyProvider(true);
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jTextFieldBarcodeInput.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldBarcodeInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBarcodeInput.setFocusCycleRoot(true);
        jTextFieldBarcodeInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tab(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Techs Currently On Duty");

        jTextAreaTechsOnDuty.setColumns(20);
        jTextAreaTechsOnDuty.setEditable(false);
        jTextAreaTechsOnDuty.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextAreaTechsOnDuty.setRows(5);
        jTextAreaTechsOnDuty.setPreferredSize(new java.awt.Dimension(700, 450));
        jTextAreaTechsOnDuty.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextAreaTechsOnDutyComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaTechsOnDuty);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Keys Currently Checked Out");

        jTextAreaKeys.setColumns(20);
        jTextAreaKeys.setEditable(false);
        jTextAreaKeys.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextAreaKeys.setRows(5);
        jTextAreaKeys.setPreferredSize(new java.awt.Dimension(700, 450));
        jScrollPane2.setViewportView(jTextAreaKeys);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBarcodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 207, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBarcodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        boolean more = false;
        String scanned = jTextFieldBarcodeInput.getText();
        jTextFieldBarcodeInput.setText("");
        jTextFieldBarcodeInput.requestFocusInWindow();
     
       
       
        if(scanned.equals("01213706"))
            shared.playSound("onestop");
        
        if(shared.isKey(scanned) || shared.isUser(scanned)){
            
            more = clock.clockObject(scanned, shared);
        
            if(more){
                 shared.playSound("beep");
                if(shared.isKeyCheckedOut(scanned)){
                clock.checkinKey(scanned);
                }
                else{
                    String user = JOptionPane.showInputDialog(null, "Please scan a user to check this out to.");
                    shared.playSound("beep");
                    clock.checkoutKey(scanned, user);
                }
            }
        }
        else{
            shared.playSound("alert");
            JOptionPane.showMessageDialog(null, "Barcode not found.");
        }
        
        jTextAreaTechsOnDuty.setText(shared.getNamesOnDuty());
        jTextAreaKeys.setText(shared.getKeysCheckedOut());
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void Tab(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tab
       
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            jButtonEnterActionPerformed(null);
    }//GEN-LAST:event_Tab

    private void jTextAreaTechsOnDutyComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextAreaTechsOnDutyComponentAdded
        jTextAreaTechsOnDuty.setText(shared.getNamesOnDuty());
    }//GEN-LAST:event_jTextAreaTechsOnDutyComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(shared s) {
        
        shared = s;

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CheckoutInterface().setVisible(true);
              
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaKeys;
    private javax.swing.JTextArea jTextAreaTechsOnDuty;
    private javax.swing.JTextField jTextFieldBarcodeInput;
    // End of variables declaration//GEN-END:variables
}
