/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adminview;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.lang.Thread;

/**
 *
 * @author phillip.oegema
 */
public class CheckoutInterface extends javax.swing.JFrame {

    static shared shared;
    clock clock = new clock();
   
    /**
     * Creates new form CheckoutInterface
     */
    public CheckoutInterface(shared s) {
            initComponents();
            shared.setupCheckout();
            jTextAreaTechsOnDuty.setText(shared.getNamesOnDuty());
            jTextAreaKeys.setText(shared.getKeysCheckedOut());      
        }
    
    private void update(){
        shared.setupCheckout();
        jTextAreaTechsOnDuty.setText(shared.getNamesOnDuty());
        jTextAreaKeys.setText(shared.getKeysCheckedOut());
    }
    
    public void begin(){
        jTextAreaTechsOnDuty.setText(shared.getNamesOnDuty());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTechsOnDuty = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaKeys = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OITKey Current Techs & Keys");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Techs Currently On Duty");

        jTextAreaTechsOnDuty.setColumns(20);
        jTextAreaTechsOnDuty.setEditable(false);
        jTextAreaTechsOnDuty.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextAreaTechsOnDuty.setRows(5);
        jTextAreaTechsOnDuty.setPreferredSize(new java.awt.Dimension(700, 450));
        jTextAreaTechsOnDuty.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextAreaTechsOnDutyComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaTechsOnDuty);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Keys Currently Checked Out");

        jTextAreaKeys.setColumns(20);
        jTextAreaKeys.setEditable(false);
        jTextAreaKeys.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextAreaKeys.setRows(5);
        jTextAreaKeys.setPreferredSize(new java.awt.Dimension(700, 450));
        jScrollPane2.setViewportView(jTextAreaKeys);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(124, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaTechsOnDutyComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextAreaTechsOnDutyComponentAdded
        jTextAreaTechsOnDuty.setText(shared.getNamesOnDuty());
    }//GEN-LAST:event_jTextAreaTechsOnDutyComponentAdded

    private void refresh(){
    while(true){
        try{
        Thread.sleep(3000);
        update();
        }catch(Exception e){}
        
        
    }
    
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        update();
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(shared s) {
        
        shared = s;

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CheckoutInterface(shared).setVisible(true);
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaKeys;
    private javax.swing.JTextArea jTextAreaTechsOnDuty;
    // End of variables declaration//GEN-END:variables
}
